twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_3_layout.html.twig']
    exception_controller: null  # Отключаем стандартный обработчик ошибок Symfony

when@test:
    twig:
        strict_variables: true
