services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: 
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Явное объявление слушателя
    App\EventListener\ExceptionListener:
        tags: [kernel.event_listener]

    App\EventListener\FixPostgreSQLDefaultSchemaListener:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }
            
            