services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: 
            - '../src/Entity/'
            - '../src/Kernel.php'



    App\EventListener\FixPostgreSQLDefaultSchemaListener:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }
            
    App\Service\BillingClient:
        arguments:
            $billingUrl: '%env(ADDRESS_BILLING)%'